# Generated by Django 5.2.4 on 2026-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_image_alter_booking_hotel_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact_info',
            field=models.CharField(max_length=15),
        ),
    ]
