# Generated by Django 5.2.4 on 2026-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotel_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=3),
        ),
    ]
