# Generated by Django 3.0.5 on 2026-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20260320_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(blank=True, help_text='Size in square meters (sqm)', null=True),
        ),
    ]
