# Generated by Django 3.0.5 on 2026-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_room_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
